---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Edit /opt/opsview/deploy/etc/user_vars.yml file using jinja template
  template:
    src: user_vars.yml.j2
    dest: /opt/opsview/deploy/etc/user_vars.yml
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0644'