---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Add text from jinja template to user_secret_content variable
  set_fact:
    user_secret_content: "{{ lookup('template', 'user_secret.yml.j2') }}"

- name: Add text to the end of /opt/opsview/deploy/etc/user_secrets.yml file
  lineinfile:
    dest: /opt/opsview/deploy/etc/user_secrets.yml
    line: "{{ user_secret_content }}"
    create: yes
    state: present
    owner: root
    group: root
    mode: '0644'