---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ lookup('env', 'REGION') }}"
    ansible_aws_ssm_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    ansible_python_interpreter: "{{ instance.python_interpreter }}"
  become: true
  tasks:
    - include_tasks: roles/primary_orchestrator/opsview_contrab_34_35_36_37/tasks/main.yaml 
      with_items: "{{ prim_orch }}"