---
- hosts: localhost
  gather_facts: false
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_region: "{{ lookup('env', 'REGION') }}"
    ansible_aws_ssm_bucket_name: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    ansible_python_interpreter: "{{ instance.python_interpreter }}"
    ansible_aws_ssm_timeout: 600
  become: true
  tasks:
    - include_tasks: roles/secondary_orchestrator/setup_infrastructure_23/tasks/main.yaml 
      with_items: "{{ sec_orch }}"