---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Save hostname of primary orchestrator to variable
  command: hostname
  register: priamry_orch_hostname

- name: Save hostname of primary orchestrator to variable 
  set_fact: primary_orch_hostname="{{ priamry_orch_hostname.stdout }}"
