---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Save hostname of secondary influx to variable
  command: hostname
  register: secondary_influx_hostname

- name: Save hostname of secondary orchestrator to variable 
  set_fact: secondary_influx_hostname="{{ secondary_influx_hostname.stdout }}"
