---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Save user_secrets_content into file
  copy:
    content: "{{ user_secrets_content }}"
    dest: /opt/opsview/deploy/etc/user_secrets.yml
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0644'

- name: Save user_vars_content into file
  copy:
    content: "{{ user_vars_content }}"
    dest: /opt/opsview/deploy/etc/user_vars.yml
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0644'