resource "aws_db_instance" "opsview" {
  depends_on           = [aws_secretsmanager_secret.rds_password]
  db_name              = "opsviewdb"
  engine               = local.engine
  engine_version       = local.engine_version
  parameter_group_name = local.parameter_group_name
  skip_final_snapshot  = true
  multi_az             = true
  /* db_subnet_group_name        = data.aws_subnet.aws_subnet_id.id */
  db_subnet_group_name = var.subnet_id
  username             = local.db_username
  password             = data.aws_secretsmanager_secret_version.rds_password.secret_string
  #manage_master_user_password   = false
  #master_user_secret_kms_key_id = data.aws_kms_key.by_id.arn
  port                       = local.port
  instance_class             = "db.t3.micro"
  storage_type               = local.storage_type
  storage_encrypted          = true
  delete_automated_backups   = false
  deletion_protection        = false
  allocated_storage          = 10
  max_allocated_storage      = 20
  auto_minor_version_upgrade = true
  backup_retention_period    = local.backup_retention
  backup_window              = local.backup_window
  copy_tags_to_snapshot      = true
  kms_key_id                 = data.aws_kms_key.by_id.arn
  tags                       = var.tags
}