---
- set_fact: ansible_aws_ssm_instance_id="{{ item.instance_id }}"

- name: Create a login user
  ansible.builtin.user:
    name: opsviewdeploy
    state: present

- name: Echo to /etc/sudoers.d/80-opsviewdeploy
  lineinfile:
    dest: /etc/sudoers.d/80-opsviewdeploy
    line: "opsviewdeploy ALL=(ALL) NOPASSWD:ALL"
    create: yes
    state: present

- name: Create .ssh directory
  file:
    path: ~opsviewdeploy/.ssh
    state: directory
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0700'

- name: Create authorized_keys file
  file:
    path: ~opsviewdeploy/.ssh/authorized_keys
    state: touch
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0600'

- name: Save id_rsa.pub to authorized_keys
  lineinfile:
    dest: ~opsviewdeploy/.ssh/authorized_keys
    line: "{{ id_rsa_pub_content }}"
    create: yes
    state: present
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0600'