---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Create /opt/opsview/coreutils/bin/check_opsview_running with check_opsview_running.j2
  template:
    src: check_opsview_running.j2
    dest: /opt/opsview/coreutils/bin/check_opsview_running
    owner: root
    group: opsview
    mode: '0655'