---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Modify /opt/opsview/deploy/etc/opsview_deploy.yml with new opsview_deploy_v2.yml.j2 template
  template:
    src: opsview_deploy_v2.yml.j2
    dest: /opt/opsview/deploy/etc/opsview_deploy.yml
    owner: root
    group: root
    mode: '0644'
