---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Modify /opt/opsview/watchdog/etc/monitrc
  lineinfile:
    dest: /opt/opsview/watchdog/etc/monitrc
    regexp: '^statefile'
    line: 'set onreboot laststate'
    insertafter: '^statefile'
    state: present
    owner: opsviewdeploy
    group: opsviewdeploy
    mode: '0600'

- name: Modify the opsview-watchdog services
  shell: |
    ls -l /opt/opsview/watchdog/etc/services | \
    egrep -v 'total|agent|cachemanager|datastore|loadbalancer|messagequeue|watchdog' | \
    awk '{print $9}' | while read config ; do \
    sed -i '/pidfile/a\    onreboot nostart' /opt/opsview/watchdog/etc/services/$config ; done

- name: Reload the opsview-watchdog configuration
  command: /opt/opsview/watchdog/bin/opsview-monit reload

- name: Stop specific opsview components
  shell: |
    ls -l  /opt/opsview/watchdog/etc/services/ \
    | egrep -v 'total|agent|cachemanager|datastore|loadbalancer|messagequeue|watchdog' | \
    awk '{print $9}' | while read component ; do \
    /opt/opsview/watchdog/bin/opsview-monit stop ${component::-5} ; done


