---
- set_fact: ansible_aws_ssm_instance_id="{{ item.id }}"

- name: Complete installation of opsview
  command: /opt/opsview/deploy/bin/opsview-deploy /opt/opsview/deploy/lib/playbooks/setup-opsview.yml